-- Create the journals table
CREATE TABLE journals (
  journal_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  journal_name VARCHAR2(200) NOT NULL,
  eissn_id VARCHAR2(20) NOT NULL,
  publication_type VARCHAR2(50) NOT NULL,
  impact_factor NUMBER(5),
  publication_frequency VARCHAR2(20),
  acceptance_rate NUMBER(5, 2),
  CONSTRAINT pk_journals_journal_id PRIMARY KEY (journal_id)
);

-- Create the issues table
CREATE TABLE issues (
  journal_id NUMBER(10) NOT NULL,
  vol_issue VARCHAR2(50) NOT NULL,
  publish_date DATE,
  CONSTRAINT pk_issues_journal_id_vol_issue PRIMARY KEY (journal_id, vol_issue),
  CONSTRAINT issues_journal_id_fk_journals FOREIGN KEY (journal_id) REFERENCES journals (journal_id)
);

-- Create the announcements table
CREATE TABLE announcements (
  journal_id NUMBER(10) NOT NULL,
  announcement_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  topic VARCHAR2(300),
  announcement VARCHAR2(1000) NOT NULL,
  announce_date DATE NOT NULL,
  CONSTRAINT pk_announcements_journal_id_accouncement_id PRIMARY KEY (journal_id, announcement_id),
  CONSTRAINT announcements_journal_id_fk_journals FOREIGN KEY (journal_id) REFERENCES journals (journal_id)
);

-- Create the users table
CREATE TABLE users (
  user_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY, 
  first_name VARCHAR2(50) NOT NULL,
  last_name VARCHAR2(50),
  gender VARCHAR2(10) NOT NULL,
  date_of_birth date,
  email VARCHAR2(200) NOT NULL,
  phone VARCHAR2(20),
  profession VARCHAR2(50),
  institute VARCHAR2(200),
  country VARCHAR2(50),
  address VARCHAR2(300),
  CONSTRAINT pk_users_user_id PRIMARY KEY (user_id),
  CONSTRAINT chk_gender CHECK (gender IN ('Male', 'Female', 'Others'))
);

-- Create the editorial table
CREATE TABLE editorial (
  journal_id NUMBER(10) NOT NULL,
  user_id NUMBER(10) NOT NULL,
  category VARCHAR2(50) NOT NULL,
  CONSTRAINT pk_editorial_journal_id_user_id PRIMARY KEY (journal_id, user_id),
  CONSTRAINT editorial_journal_id_fk_journals FOREIGN KEY (journal_id) REFERENCES journals (journal_id),
  CONSTRAINT editorial_user_id_fk_users FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Create the articles table
CREATE TABLE articles (
  journal_id NUMBER(10) NOT NULL,
  article_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY, 
  vol_issue VARCHAR2(20) NOT NULL,
  article_title VARCHAR2(300) NOT NULL,
  abstract VARCHAR2(1000) NOT NULL,
  article_type VARCHAR2(50) NOT NULL,
  keywords VARCHAR2(200),
  doi_id VARCHAR2(100),
  author NUMBER(10) NOT NULL,
  crosponding_author NUMBER(10),
  published_date DATE NOT NULL,
  CONSTRAINT pk_articles_article_id PRIMARY KEY (article_id),
  --CONSTRAINT articles_journal_id_fk_journals FOREIGN KEY (journal_id) REFERENCES issues (journal_id),
  CONSTRAINT articles_journal_id_vol_issue_fk_issues FOREIGN KEY (journal_id, vol_issue) REFERENCES issues (journal_id, vol_issue),
  CONSTRAINT articles_author_fk_users FOREIGN KEY (author) REFERENCES users (user_id),
  CONSTRAINT articles_crosponding_author_fk_users FOREIGN KEY (crosponding_author) REFERENCES users (user_id)
);
